version: '3'

services:
  api:
    build: Backend
    restart: always
    volumes:
      - ./Backend/bin/www
    ports:
      - 3000:3000

  client:
    build: Frontend
    restart: always
    ports:
      - 8080:8080
